linters:
  HtmlAttributeQuotes:
    enabled: true
    enforce_single_quotes: false

exclude:
  - 'vendor/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'node_modules/**/*'
  - 'bin/*'
  - '**/Gemfile'
  - '.git/**/*'
